/*
  Adrenaline
  Copyright (C) 2016-2018, TheFloW

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#define N_FILES (sizeof(files) / sizeof(char **))

char *files[] = {
  // "/codepage/cptbl.dat",
  // "/data/cert/CA_LIST.cer",
  // "/font/gb3s1518.bwfon",
  // "/font/imagefont.bin",
  // "/font/jpn0.pgf",
  // "/font/kr0.pgf",
  // "/font/ltn0.pgf",
  // "/font/ltn1.pgf",
  // "/font/ltn10.pgf",
  // "/font/ltn11.pgf",
  // "/font/ltn12.pgf",
  // "/font/ltn13.pgf",
  // "/font/ltn14.pgf",
  // "/font/ltn15.pgf",
  // "/font/ltn2.pgf",
  // "/font/ltn3.pgf",
  // "/font/ltn4.pgf",
  // "/font/ltn5.pgf",
  // "/font/ltn6.pgf",
  // "/font/ltn7.pgf",
  // "/font/ltn8.pgf",
  // "/font/ltn9.pgf",
  // "/kd/amctrl.prx",
  // "/kd/audiocodec_260.prx",
  "/kd/avcodec.prx",
  // "/kd/cert_loader.prx",
  // "/kd/chkreg.prx",
  // "/kd/chnnlsv.prx",
  "/kd/dmacman.prx",
  "/kd/exceptionman.prx",
  // "/kd/exitgame.prx",
  // "/kd/g729.prx",
  "/kd/ge.prx",
  "/kd/ge_2.prx",
  // "/kd/http_storage.prx",
  // "/kd/ifhandle.prx",
  // "/kd/impose_kermit.prx",
  "/kd/init.prx",
  "/kd/interruptman.prx",
  "/kd/iofilemgr.prx",
  // "/kd/iofilemgr_dnas.prx",
  // "/kd/isofs.prx",
  "/kd/kermit.prx",
  "/kd/kermit_audio.prx",
  "/kd/kermit_ctrl.prx",
  "/kd/kermit_display.prx",
  "/kd/kermit_flashfs.prx",
  "/kd/kermit_hpremote.prx",
  // "/kd/kermit_idstorage.prx",
  "/kd/kermit_lowio.prx",
  "/kd/kermit_me_wrapper.prx",
  "/kd/kermit_me_wrapper_2.prx",
  "/kd/kermit_msemu.prx",
  "/kd/kermit_msfs.prx",
  "/kd/kermit_peripheral.prx",
  "/kd/kermit_power.prx",
  "/kd/kermit_rtc.prx",
  "/kd/kermit_usb.prx",
  "/kd/kermit_utility.prx",
  "/kd/kermit_wlan.prx",
  // "/kd/libaac.prx",
  // "/kd/libasfparser.prx",
  // "/kd/libatrac3plus.prx",
  // "/kd/libaudiocodec2.prx",
  // "/kd/libdnas.prx",
  // "/kd/libdnas_core.prx",
  // "/kd/libgameupdate.prx",
  // "/kd/libhttp.prx",
  // "/kd/libmp3.prx",
  // "/kd/libmp4.prx",
  // "/kd/libparse_http.prx",
  // "/kd/libparse_uri.prx",
  // "/kd/libssl.prx",
  // "/kd/libupdown.prx",
  "/kd/loadcore.prx",
  "/kd/loadexec_01g.prx",
  // "/kd/mcctrl.prx",
  // "/kd/mediasync.prx",
  // "/kd/memab.prx",
  "/kd/memlmd_01g.prx",
  "/kd/mesg_led_01g.prx",
  // "/kd/mgvideo.prx",
  "/kd/modulemgr.prx",
  // "/kd/mp4msv.prx",
  // "/kd/mpeg.prx",
  "/kd/mpegbase_260.prx",
  // "/kd/np.prx",
  // "/kd/np_auth.prx",
  // "/kd/np_commerce2.prx",
  // "/kd/np_commerce2_regcam.prx",
  // "/kd/np_commerce2_store.prx",
  // "/kd/np_core.prx",
  // "/kd/np_inst.prx",
  // "/kd/np_matching2.prx",
  // "/kd/np_service.prx",
  // "/kd/np9660.prx",
  // "/kd/npdrm.prx",
  // "/kd/openpsid.prx",
  "/kd/pops_01g.prx",
  "/kd/popsman.prx",
  // "/kd/psheet.prx",
  // "pspbtcnf.bin",
  "/kd/pspnet.prx",
  "/kd/pspnet_adhoc.prx",
  "/kd/pspnet_adhoc_auth.prx",
  "/kd/pspnet_adhoc_discover.prx",
  "/kd/pspnet_adhoc_download.prx",
  "/kd/pspnet_adhoc_matching.prx",
  "/kd/pspnet_adhoc_transfer_int.prx",
  "/kd/pspnet_adhocctl.prx",
  "/kd/pspnet_apctl.prx",
  "/kd/pspnet_inet.prx",
  "/kd/pspnet_resolver.prx",
  "/kd/pspnet_upnp.prx",
  "/kd/pspnet_wispr.prx",
  "/kd/registry.prx",
  // "/kd/resource/impose.rsc",
  // "/kd/sc_sascore.prx",
  // "/kd/sircs.prx",
  "/kd/sysmem.prx",
  "/kd/systimer.prx",
  "/kd/threadman.prx",
  "/kd/usbacc.prx",
  "/kd/usbcam.prx",
  "/kd/usbgps.prx",
  "/kd/usbmic.prx",
  "/kd/usbpspcm.prx",
  // "/kd/usersystemlib.prx",
  // "/kd/vaudio.prx",
  // "/kd/videocodec_260.prx",
  "/vsh/etc/index_01g.dat",
  "/vsh/etc/version.txt",
  // "/vsh/module/auth_plugin.prx",
  // "/vsh/module/auto_connect.prx",
  // "/vsh/module/common_gui.prx",
  // "/vsh/module/common_util.prx",
  // "/vsh/module/dd_helper_utility.prx",
  // "/vsh/module/dialogmain.prx",
  // "/vsh/module/dnas_plugin.prx",
  // "/vsh/module/file_parser_base.prx",
  // "/vsh/module/game_install_plugin.prx",
  // "/vsh/module/htmlviewer_ui.prx",
  // "/vsh/module/htmlviewer_utility.prx",
  // "/vsh/module/hvauth_r.prx",
  "/vsh/module/kermit_netconf_dialog.prx",
  "/vsh/module/kermit_osk_plugin.prx",
  // "/vsh/module/libfont_hv.prx",
  // "/vsh/module/libpspvmc.prx",
  // "/vsh/module/libslim.prx",
  // "/vsh/module/libwww.prx",
  // "/vsh/module/msgdialog_plugin.prx",
  "/vsh/module/netconf_plugin.prx",
  // "/vsh/module/netfront.prx",
  // "/vsh/module/netplay_server_plus_utility.prx",
  // "/vsh/module/netplay_server_utility.prx",
  // "/vsh/module/netplay_server2_utility.prx",
  // "/vsh/module/npinstaller_plugin.prx",
  // "/vsh/module/npsignin_plugin.prx",
  // "/vsh/module/npsignup_plugin.prx",
  // "/vsh/module/pafmini.prx",
  // "/vsh/module/ps3scan_plugin.prx",
  // "/vsh/module/psn_utility.prx",
  // "/vsh/module/savedata_auto_dialog.prx",
  // "/vsh/module/savedata_utility.prx",
  // "/vsh/module/screenshot_plugin.prx",
  // "/vsh/module/store_browser_plugin.prx",
  // "/vsh/module/store_checkout_plugin.prx",
  // "/vsh/module/store_checkout_utility.prx",
  // "/vsh/resource/auth_plugin.rco",
  // "/vsh/resource/dd_helper.rco",
  // "/vsh/resource/dnas_plugin.rco",
  // "/vsh/resource/game_install_plugin.rco",
  // "/vsh/resource/htmlviewer.res",
  // "/vsh/resource/msgdialog_plugin.rco",
  // "/vsh/resource/netconf_dialog.rco",
  // "/vsh/resource/netplay_plugin.rco",
  // "/vsh/resource/npinstaller_plugin.rco",
  // "/vsh/resource/npsignin_plugin.rco",
  // "/vsh/resource/npsignup_plugin.rco",
  // "/vsh/resource/ps3scan_plugin.rco",
  // "/vsh/resource/psn_plugin.rco",
  // "/vsh/resource/savedata_utility.rco",
  // "/vsh/resource/screenshot_plugin.rco",
  // "/vsh/resource/store_browser_plugin.rco",
  // "/vsh/resource/store_checkout_plugin.rco",
  // "/vsh/resource/system_plugin.rco",
  // "/vsh/resource/system_plugin_fg.rco",
};